version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: automatic-barber
    restart: unless-stopped
    env_file: .env
    environment:
      PORT: "8080"
    ports:
      - 80:8080